#controllers:
#   resource:
#      path: ../src/Controller/
#        namespace: App\Controller
#    type: attribute

app_prueba:
    path: /persona
    controller: App\Controller\PersonaController::persona