DROP TABLE IF EXISTS TUTORIAS_IMPARTE;
DROP TABLE IF EXISTS TUTORIAS_CURSOS;
DROP TABLE IF EXISTS TUTORIAS_TUTORIAS;
DROP TABLE IF EXISTS TUTORIAS_NIVELES;
DROP TABLE IF EXISTS TUTORIAS_ASIGNATURAS;
DROP TABLE IF EXISTS TUTORIAS_PROFESORES;


CREATE TABLE TUTORIAS_PROFESORES
	(
	PROFESOR_ID INTEGER NOT NULL AUTO_INCREMENT ,
	NOMBRE VARCHAR(20)  NOT NULL ,
	APELLIDOS VARCHAR(10)  NOT NULL ,
	PRIMARY KEY(PROFESOR_ID)
	);
CREATE TABLE TUTORIAS_NIVELES
	(
	NIVEL_ID INTEGER NOT NULL AUTO_INCREMENT,
	NIVEL VARCHAR(10)  NOT NULL ,
	ORDEN INTEGER,
	PRIMARY KEY(NIVEL_ID)
	);
CREATE TABLE TUTORIAS_CURSOS
	(
	CURSO_ID INTEGER NOT NULL AUTO_INCREMENT ,
	CURSO VARCHAR(10)  NOT NULL ,
	NIVEL_ID INTEGER  ,
	TUTOR_ID INTEGER  ,
	ORDEN INTEGER,
	PRIMARY KEY(CURSO_ID) ,
	FOREIGN KEY ( TUTOR_ID ) REFERENCES TUTORIAS_PROFESORES( PROFESOR_ID ),
	FOREIGN KEY ( NIVEL_ID ) REFERENCES TUTORIAS_NIVELES( NIVEL_ID )
	);



CREATE TABLE TUTORIAS_ASIGNATURAS
	(
	ASIGNATURA_ID INTEGER NOT NULL AUTO_INCREMENT ,
	ASIGNATURA VARCHAR(20)  NOT NULL ,
	PRIMARY KEY(ASIGNATURA_ID)
	);
	
CREATE TABLE TUTORIAS_IMPARTE
	(
	ASIGNATURA_ID INTEGER,
	PROFESOR_ID INTEGER  ,
	CURSO_ID INTEGER,
	FOREIGN KEY ( ASIGNATURA_ID ) REFERENCES TUTORIAS_ASIGNATURAS( ASIGNATURA_ID ),
	FOREIGN KEY ( PROFESOR_ID ) REFERENCES TUTORIAS_PROFESORES(PROFESOR_ID ),
	FOREIGN KEY ( CURSO_ID ) REFERENCES TUTORIAS_CURSOS( CURSO_ID )
	);



CREATE TABLE TUTORIAS_TUTORIAS
	(
	PROFESOR_ID INTEGER NOT NULL,
	HORA TIME ,
	DIA      ENUM('L','M', 'X','J', 'V'),
	FOREIGN KEY ( PROFESOR_ID ) REFERENCES TUTORIAS_PROFESORES( PROFESOR_ID )
	);

INSERT INTO TUTORIAS_NIVELES ( NIVEL, ORDEN ) VALUES ( '1ESO',1);
INSERT INTO TUTORIAS_NIVELES ( NIVEL, ORDEN ) VALUES ( '2ESO',2);
INSERT INTO TUTORIAS_NIVELES ( NIVEL, ORDEN ) VALUES ( '3ESO',3);
INSERT INTO TUTORIAS_NIVELES ( NIVEL, ORDEN ) VALUES ( '4ESO',4);
INSERT INTO TUTORIAS_NIVELES ( NIVEL, ORDEN ) VALUES ( '1BACH',5);
INSERT INTO TUTORIAS_NIVELES ( NIVEL, ORDEN ) VALUES ( '2BACH',6);

INSERT INTO TUTORIAS_PROFESORES ( NOMBRE, APELLIDOS ) VALUES ( 'JAVIER',"LOPEZ");
INSERT INTO TUTORIAS_PROFESORES ( NOMBRE, APELLIDOS ) VALUES ( 'ANTONIO',"LOPEZ");
INSERT INTO TUTORIAS_PROFESORES ( NOMBRE, APELLIDOS ) VALUES ( 'JULAIN',"LOPEZ");
INSERT INTO TUTORIAS_PROFESORES ( NOMBRE, APELLIDOS ) VALUES ( 'SUSANA',"LOPEZ");
INSERT INTO TUTORIAS_PROFESORES ( NOMBRE, APELLIDOS ) VALUES ( 'ISABEL',"LOPEZ");
INSERT INTO TUTORIAS_PROFESORES ( NOMBRE, APELLIDOS ) VALUES ( 'ALBERTO',"LOPEZ");
INSERT INTO TUTORIAS_PROFESORES ( NOMBRE, APELLIDOS ) VALUES ( 'PABLO',"LOPEZ");
INSERT INTO TUTORIAS_PROFESORES ( NOMBRE, APELLIDOS ) VALUES ( 'LUCIANO',"LOPEZ");
INSERT INTO TUTORIAS_PROFESORES ( NOMBRE, APELLIDOS ) VALUES ( 'PEDRO',"LOPEZ");
INSERT INTO TUTORIAS_PROFESORES ( NOMBRE, APELLIDOS ) VALUES ( 'ANDRES',"LOPEZ");
INSERT INTO TUTORIAS_PROFESORES ( NOMBRE, APELLIDOS ) VALUES ( 'LUIS',"LOPEZ");
INSERT INTO TUTORIAS_PROFESORES ( NOMBRE, APELLIDOS ) VALUES ( 'JAIME',"LOPEZ");
INSERT INTO TUTORIAS_PROFESORES ( NOMBRE, APELLIDOS ) VALUES ( 'OLGA',"LOPEZ");
INSERT INTO TUTORIAS_PROFESORES ( NOMBRE, APELLIDOS ) VALUES ( 'MARIA',"LOPEZ");


INSERT INTO TUTORIAS_ASIGNATURAS ( ASIGNATURA ) VALUES ( "MATEMATICAS");
INSERT INTO TUTORIAS_ASIGNATURAS ( ASIGNATURA ) VALUES ( "LENGUA");
INSERT INTO TUTORIAS_ASIGNATURAS ( ASIGNATURA ) VALUES ( "HISTORIA");
INSERT INTO TUTORIAS_ASIGNATURAS ( ASIGNATURA ) VALUES ( "INGLES");
INSERT INTO TUTORIAS_ASIGNATURAS ( ASIGNATURA ) VALUES ( "DIBUJO");
INSERT INTO TUTORIAS_ASIGNATURAS ( ASIGNATURA ) VALUES ( "FRANCES");


INSERT INTO TUTORIAS_CURSOS ( CURSO, NIVEL_ID, TUTOR_ID ) VALUES ( '1ESO-A', 1, 1);
INSERT INTO TUTORIAS_CURSOS ( CURSO, NIVEL_ID, TUTOR_ID ) VALUES ( '1ESO-B', 1, 2);

INSERT INTO TUTORIAS_CURSOS ( CURSO, NIVEL_ID, TUTOR_ID ) VALUES ( '2ESO-A', 2, 3);
INSERT INTO TUTORIAS_CURSOS ( CURSO, NIVEL_ID, TUTOR_ID ) VALUES ( '2ESO-B', 2, 4);

INSERT INTO TUTORIAS_CURSOS ( CURSO, NIVEL_ID, TUTOR_ID ) VALUES ( '3ESO-A', 3, 5);
INSERT INTO TUTORIAS_CURSOS ( CURSO, NIVEL_ID, TUTOR_ID ) VALUES ( '3ESO-B', 3, 6);

INSERT INTO TUTORIAS_CURSOS ( CURSO, NIVEL_ID, TUTOR_ID ) VALUES ( '4ESO-A', 4, 7);
INSERT INTO TUTORIAS_CURSOS ( CURSO, NIVEL_ID, TUTOR_ID ) VALUES ( '4ESO-B', 4, 8);

INSERT INTO TUTORIAS_CURSOS ( CURSO, NIVEL_ID, TUTOR_ID ) VALUES ( '1BACH-A', 5, 9);
INSERT INTO TUTORIAS_CURSOS ( CURSO, NIVEL_ID, TUTOR_ID ) VALUES ( '1BACH-B', 5, 10);

INSERT INTO TUTORIAS_CURSOS ( CURSO, NIVEL_ID, TUTOR_ID ) VALUES ( '2BACH-A', 6, 11);
INSERT INTO TUTORIAS_CURSOS ( CURSO, NIVEL_ID, TUTOR_ID ) VALUES ( '2BACH-B', 6, 12);


INSERT INTO `tutorias_tutorias` (`PROFESOR_ID`, `HORA`, `DIA`) VALUES ('1', '10:00', 'L');
INSERT INTO `tutorias_tutorias` (`PROFESOR_ID`, `HORA`, `DIA`) VALUES ('2', '11:00', 'M');
INSERT INTO `tutorias_tutorias` (`PROFESOR_ID`, `HORA`, `DIA`) VALUES ('3', '10:00', 'L');
INSERT INTO `tutorias_tutorias` (`PROFESOR_ID`, `HORA`, `DIA`) VALUES ('4', '11:00', 'M');
INSERT INTO `tutorias_tutorias` (`PROFESOR_ID`, `HORA`, `DIA`) VALUES ('5', '10:00', 'L');
INSERT INTO `tutorias_tutorias` (`PROFESOR_ID`, `HORA`, `DIA`) VALUES ('6', '11:00', 'M');
INSERT INTO `tutorias_tutorias` (`PROFESOR_ID`, `HORA`, `DIA`) VALUES ('7', '10:00', 'L');
INSERT INTO `tutorias_tutorias` (`PROFESOR_ID`, `HORA`, `DIA`) VALUES ('8', '11:00', 'M');
INSERT INTO `tutorias_tutorias` (`PROFESOR_ID`, `HORA`, `DIA`) VALUES ('9', '10:00', 'L');
INSERT INTO `tutorias_tutorias` (`PROFESOR_ID`, `HORA`, `DIA`) VALUES ('10', '11:00', 'M');
INSERT INTO `tutorias_tutorias` (`PROFESOR_ID`, `HORA`, `DIA`) VALUES ('11', '11:00', 'M');
INSERT INTO `tutorias_tutorias` (`PROFESOR_ID`, `HORA`, `DIA`) VALUES ('12', '11:00', 'M');
INSERT INTO `tutorias_tutorias` (`PROFESOR_ID`, `HORA`, `DIA`) VALUES ('13', '11:00', 'M');
INSERT INTO `tutorias_tutorias` (`PROFESOR_ID`, `HORA`, `DIA`) VALUES ('14', '11:00', 'M');

INSERT INTO `tutorias_imparte` (`ASIGNATURA_ID`, `PROFESOR_ID`, `CURSO_ID`) VALUES ('1', '1', '1');
INSERT INTO `tutorias_imparte` (`ASIGNATURA_ID`, `PROFESOR_ID`, `CURSO_ID`) VALUES ('2', '2', '1');
INSERT INTO `tutorias_imparte` (`ASIGNATURA_ID`, `PROFESOR_ID`, `CURSO_ID`) VALUES ('3', '3', '1');
INSERT INTO `tutorias_imparte` (`ASIGNATURA_ID`, `PROFESOR_ID`, `CURSO_ID`) VALUES ('4', '4', '1');
INSERT INTO `tutorias_imparte` (`ASIGNATURA_ID`, `PROFESOR_ID`, `CURSO_ID`) VALUES ('5', '5', '1');

INSERT INTO `tutorias_imparte` (`ASIGNATURA_ID`, `PROFESOR_ID`, `CURSO_ID`) VALUES ('1', '6', '2');
INSERT INTO `tutorias_imparte` (`ASIGNATURA_ID`, `PROFESOR_ID`, `CURSO_ID`) VALUES ('2', '7', '2');
INSERT INTO `tutorias_imparte` (`ASIGNATURA_ID`, `PROFESOR_ID`, `CURSO_ID`) VALUES ('3', '8', '2');
INSERT INTO `tutorias_imparte` (`ASIGNATURA_ID`, `PROFESOR_ID`, `CURSO_ID`) VALUES ('4', '9', '2');
INSERT INTO `tutorias_imparte` (`ASIGNATURA_ID`, `PROFESOR_ID`, `CURSO_ID`) VALUES ('5', '10', '2');

INSERT INTO `tutorias_imparte` (`ASIGNATURA_ID`, `PROFESOR_ID`, `CURSO_ID`) VALUES ('1', '1', '3');
INSERT INTO `tutorias_imparte` (`ASIGNATURA_ID`, `PROFESOR_ID`, `CURSO_ID`) VALUES ('2', '2', '3');
INSERT INTO `tutorias_imparte` (`ASIGNATURA_ID`, `PROFESOR_ID`, `CURSO_ID`) VALUES ('3', '3', '3');
INSERT INTO `tutorias_imparte` (`ASIGNATURA_ID`, `PROFESOR_ID`, `CURSO_ID`) VALUES ('4', '4', '3');
INSERT INTO `tutorias_imparte` (`ASIGNATURA_ID`, `PROFESOR_ID`, `CURSO_ID`) VALUES ('5', '5', '3');

INSERT INTO `tutorias_imparte` (`ASIGNATURA_ID`, `PROFESOR_ID`, `CURSO_ID`) VALUES ('1', '6', '4');
INSERT INTO `tutorias_imparte` (`ASIGNATURA_ID`, `PROFESOR_ID`, `CURSO_ID`) VALUES ('2', '7', '4');
INSERT INTO `tutorias_imparte` (`ASIGNATURA_ID`, `PROFESOR_ID`, `CURSO_ID`) VALUES ('3', '8', '4');
INSERT INTO `tutorias_imparte` (`ASIGNATURA_ID`, `PROFESOR_ID`, `CURSO_ID`) VALUES ('4', '9', '4');
INSERT INTO `tutorias_imparte` (`ASIGNATURA_ID`, `PROFESOR_ID`, `CURSO_ID`) VALUES ('5', '10', '4');

